(function () {
  const genzUiText = {
    language: 'Lingo',
    searchPlaceholder: 'Stalk pods / eps',
    clearSearch: 'Yeet search',
    surprise: 'Plot twist',
    share: 'Put the GC on',
    refresh: 'Vibe check',
    empty: 'Deadass nothing here bestie.',
    backToTop: 'Yeet to top',
    open: 'Pop open',
    copyLink: 'Snatch link',
    linkCopied: 'Link secured',
    copyTitle: 'Snatch title',
    titleCopied: 'Title secured',
    playEpisode: 'Let it rip',
    closePlayer: 'Kill player',
    history: 'Lore',
    closeHistory: 'Hide the receipts',
    favorite: 'Stan',
    unfavorite: 'Unstan',
    favoriteAdded: 'Locked in',
    favoriteRemoved: 'Yeeted',
    rankUpdateTitle: 'Tier list update',
    loadFailedRefresh: 'Big yikes, it broke. Refresh maybe?',
    loadingDots: 'Cooking...',
    loadingData: 'Cooking up the data...',
    refreshingData: 'Vibe checking data...',
    ready: 'Good to go',
    cache: 'Stash',
    cached: 'Stashed',
    refreshing: 'Vibe checking',
    loading: 'Cooking',
    live: 'IRL',
    retry: 'Run it back',
    noSource: "Ain't no source for this, chief.",
    noData: "It's giving nothing right now.",
    platformApple: 'Apple Pods',
    platformSpotify: 'Spotify Pods',
    platformYoutube: 'YT Pods',
    platformAudible: 'Audible Pods',
    platformIheartRadio: 'iHeartRadio Pods',
    platformSiriusxm: 'SiriusXM Pods',
    platformPandora: 'Pandora Pods',
    platformPodcastApp: 'Pod App Pods',
    platformRtlPlus: 'RTL+ Pods',
    platformTuneIn: 'TuneIn Pods',
    platformXimalaya: 'Ximalaya Pods',
    platformBilibili: 'BiliBili Pods',
    platformBbcSounds: 'BBC Sounds Pods',
    platformRadionet: 'radio.net Pods',
    platformAbclisten: 'ABC listen Pods',
    platformNrk: 'NRK Radio Pods',
    platformYleAreena: 'Yle Areena Pods',
    platformSverigesRadio: 'Sveriges Radio Pods',
    platformCastbox: 'Castbox Pods',
    platformPocketcasts: 'Pocket Casts Pods',
    platformAmazonmusic: 'Amazon Music Pods',
    platformPodbbang: 'podbbang Pods',
    platformAudioclip: 'audioclip Pods',
    platformArdsounds: 'ARD Sounds',
    platformRadiofrance: 'Radio France',
    platformDeezer: 'Deezer Pods',
    platformPodimo: 'Podimo Pods',
    platformPodcastAddict: 'Pod Addict Pods',
    platformRadiko: 'radiko Pods',
    platformIvoox: 'iVoox Pods',
    platformAll: 'Every Platform',
    topPodcasts: 'Goated Pods',
    topEpisodes: 'Goated Eps',
    typeTrending: 'Popping Off Pods',
    typeArts: 'Artsy Vibes',
    typeBusiness: 'Hustle Culture',
    typeComedy: "I'm Dead",
    typeEducation: 'Brain Gains',
    typeFiction: 'Made Up Lore',
    typeHealthFitness: 'Gym Bro & Wellness',
    typeHistory: 'Ancient Lore',
    typeLeisure: 'Chilling',
    typeMusic: 'Bops & Bangers',
    typeNews: 'The Tea',
    typeReligionSpirituality: 'Holy Vibes',
    typeScience: 'Nerd Stuff',
    typeSocietyCulture: 'Touch Grass',
    typeSports: 'Sportsball',
    typeTechnology: 'Tech Bro Vibes',
    typeTrueCrime: 'Sus AF',
    typeTvFilm: 'Bingeing',
    typeTopSubscriberShows: 'Top Sub Shows',
    typeTopSubscriberChannels: 'Top Sub Channels',
    typeBooks: 'BookTok',
    typeDesign: 'Aesthetics',
    typeFashionBeauty: 'Fits & Glam',
    typeFood: 'Eats',
    typePerformingArts: 'Theater Kid Energy',
    typeVisualArts: 'Visuals',
    typeCareers: '9 to 5 Grind',
    typeEntrepreneurship: 'CEO Mindset',
    typeInvesting: 'Stonks',
    typeManagement: 'Bossing Up',
    typeMarketing: 'Clout Chasing',
    typeNonProfit: 'Doing Good',
    typeComedyInterviews: 'Funny Yapping',
    typeImprov: 'Winging It',
    typeStandUp: 'Stand-Up',
    typeCourses: 'Classes',
    typeHowTo: 'Tutorials',
    typeLanguageLearning: 'Duolingo Vibes',
    typeSelfImprovement: 'Glow Up',
    typeComedyFiction: 'Funny Lore',
    typeDrama: 'The Drama',
    typeScienceFiction: 'Sci-Fi',
    typeGovernment: 'Gov Stuff',
    typeAlternativeHealth: 'Alt Wellness',
    typeFitness: 'Gains',
    typeMedicine: 'Med Stuff',
    typeMentalHealth: 'Mental Health Check',
    typeNutrition: 'Macros',
    typeSexuality: 'Spicy Talk',
    typeKidsFamily: 'Fam & Kiddos',
    typeEducationForKids: 'Brain Gains for Kids',
    typeParenting: 'Raising Crotch Goblins',
    typePetsAnimals: 'Fur Babies',
    typeStoriesForKids: 'Kid Lore',
    typeAnimationManga: 'Weeb Stuff',
    typeAutomotive: 'Car Bros',
    typeAviation: 'Plane Geeks',
    typeCrafts: 'DIYs',
    typeGames: 'Tabletop',
    typeHobbies: 'Side Quests',
    typeHomeGarden: 'Plant Parent Vibes',
    typeVideoGames: 'Gaming',
    typeMusicCommentary: 'Music Takes',
    typeMusicHistory: 'Music Lore',
    typeMusicInterviews: 'Artist Yapping',
    typeBusinessNews: 'Money Tea',
    typeDailyNews: 'Daily Tea',
    typeEntertainmentNews: 'Pop Culture Tea',
    typeNewsCommentary: 'Hot Takes',
    typePolitics: 'Politi-tea',
    typeSportsNews: 'Sports Tea',
    typeTechNews: 'Tech Tea',
    typeBuddhism: 'Buddhism',
    typeChristianity: 'Christianity',
    typeHinduism: 'Hinduism',
    typeIslam: 'Islam',
    typeJudaism: 'Judaism',
    typeReligion: 'Religion',
    typeSpirituality: 'Spiritual Vibes',
    typeAstronomy: 'Space Stuff',
    typeChemistry: 'Chem',
    typeEarthSciences: 'Earth Stuff',
    typeLifeSciences: 'Bio Stuff',
    typeMathematics: 'Math',
    typeNaturalSciences: 'Nature Science',
    typeNature: 'Touching Grass',
    typePhysics: 'Physics',
    typeSocialSciences: 'Social Science',
    typeDocumentary: 'Docs',
    typePersonalJournals: 'Trauma Dumping',
    typePhilosophy: 'Deep Thoughts',
    typePlacesTravel: 'Wanderlust',
    typeRelationships: 'Situationships',
    typeBaseball: 'Baseball',
    typeBasketball: 'Hoops',
    typeCricket: 'Cricket',
    typeFantasySports: 'Fantasy Sports',
    typeFootball: 'Football',
    typeGolf: 'Golf',
    typeHockey: 'Hockey',
    typeRugby: 'Rugby',
    typeRunning: 'Running',
    typeSoccer: 'Soccer',
    typeSwimming: 'Swimming',
    typeTennis: 'Tennis',
    typeVolleyball: 'Volleyball',
    typeWilderness: 'The Wild',
    typeWrestling: 'Wrestling',
    typeAfterShows: 'Post-Binge Yapping',
    typeFilmHistory: 'Movie Lore',
    typeFilmInterviews: 'Movie Yapping',
    typeFilmReviews: 'Movie Takes',
    typeTvReviews: 'TV Takes',
    periodLabel: 'Era',
    periodDaily: 'Daily',
    periodWeek: 'Weekly',
    periodMonth: 'Monthly',
    periodYear: 'Yearly',
    periodAll: 'All-time GOAT',
    allPlatform: 'Every Platform',
    languageChart: 'Lingo Chart',
    'scope.country': 'Lingo Chart',
    'scope.myPodcasts': 'My Pods',
    'scope.lang-en': 'English Pods',
    'scope.lang-zh': 'Chinese Pods',
    'scope.lang-es': 'Spanish Pods',
    'scope.lang-ar': 'Arabic Pods',
    'scope.lang-fr': 'French Pods',
    'scope.lang-pt': 'Portuguese Pods',
    'scope.lang-de': 'German Pods',
    'scope.lang-nl': 'Dutch Pods',
    dateLabel: 'Date',
    dateLatest: 'Freshest',
    reminderNeedToday: "No snapshot saved for today yet. Check today's chart and vibe check it.",
    reminderSavedToday: "Today's snapshot is locked in.",
    myPodcasts: 'My Pods',
    podcastsWord: 'Pods',
    episodesWord: 'Eps',
    notesWord: 'Yaps',
    myPodcastsImportGroupLabel: 'My Pods',
    myPodcastsImportRss: 'RSS',
    myPodcastsImportYoutube: 'YT',
    myPodcastsImportApple: 'Apple',
    myPodcastsImportSpotify: 'Spotify',
    myPodcastsImportOpml: 'OPML',
    myPodcastsImportActionRss: 'RSS',
    myPodcastsImportActionYoutube: 'YT',
    myPodcastsImportActionApple: 'Apple',
    myPodcastsImportActionSpotify: 'Spotify',
    myPodcastsImportActionOpml: 'OPML',
    myPodcastsImportPlaceholderRss: 'RSS',
    myPodcastsImportPlaceholderYoutube: 'YT',
    myPodcastsImportPlaceholderApple: 'Apple',
    myPodcastsImportPlaceholderSpotify: 'Spotify',
    myPodcastsImportPickOpml: 'OPML',
    myPodcastsImportFailed: 'Big yikes, it flopped. Refresh and try again bestie.',
    note: 'Yap',
    closeNote: 'Kill yap',
    notePlaceholder: 'Drop your thoughts bestie...',
    noteSaved: 'Yap secured',
    noteDeleted: 'Yap yeeted',
    noteEmptyExport: 'Drop a yap first',
    noteUnsaved: 'Unsaved vibes',
    noteSaving: 'Cooking...',
    noteDone: 'Bet',
    noteDelete: 'Yeet',
    noteSave: 'Lock in',
    noteDownload: 'Snag',
    noteDownloadMd: 'Markdown (.md)',
    noteDownloadTxt: 'Text (.txt)',
    noteCopy: 'Snag',
    noteCopied: 'Yap snagged',
    noteLastSaved: 'Last locked in',
    noteNew: 'No yaps yet',
    noteFor: 'Yap for',
    noteDownloaded: 'Yap snagged',
    close: 'Kill',
    previous: 'Back',
    next: 'Next',
    playlist: 'Playlist',
    playlistMode: 'Playlist Mode',
    refreshPlayer: 'Vibe check player',
    sponsored: '#Ad',
    ximalayaStoryPodcasts: 'Story Pods',
    ximalayaOpinionPodcasts: 'Hot Take Pods',
    'runtime.fallbackPodcast': 'Pod',
    'runtime.fallbackPodcasts': 'Pods',
    'runtime.youtubeFallbackTitlePlaylist': 'YT Playlist',
    'runtime.youtubeFallbackTitleVideo': 'YT Vid',
    'runtime.youtubeFallbackTitleChannel': 'YT Channel',
    'runtime.youtubeFallbackPublisher': 'YT',
    'runtime.appleBrandLabel': 'Apple Pods',
    'runtime.spotifyBrandLabel': 'Spotify',
    'runtime.applePodcastChannels': 'Apple Pod Channels'
  };

  window.ENGLISH_TEXT_MODES = Object.assign({}, window.ENGLISH_TEXT_MODES, {
    genz: {
      uiText: genzUiText
    }
  });
}());
