(function () {
  const genzUiText = {
    language: 'Lingo',
    searchPlaceholder: 'Stalk pods / eps',
    clearSearch: 'Yeet search',
    surprise: 'Plot twist',
    share: 'Put the GC on',
    refresh: 'Vibe check',
    empty: 'Deadass nothing here bestie.',
    backToTop: 'Yeet to top',
    open: 'Pop open',
    copyLink: 'Snatch link',
    linkCopied: 'Link secured',
    copyTitle: 'Snatch title',
    titleCopied: 'Title secured',
    playEpisode: 'Let it rip',
    closePlayer: 'Kill player',
    history: 'Lore',
    closeHistory: 'Hide the receipts',
    favorite: 'Stan',
    unfavorite: 'Unstan',
    favoriteAdded: 'Locked in',
    favoriteRemoved: 'Yeeted',
    rankUpdateTitle: 'Tier list update',
    loadFailedRefresh: 'Big yikes, it broke. Refresh maybe?',
    loadingDots: 'Cooking...',
    loadingData: 'Cooking up the data...',
    refreshingData: 'Vibe checking data...',
    ready: 'Good to go',
    cache: 'Stash',
    cached: 'Stashed',
    refreshing: 'Vibe checking',
    loading: 'Cooking',
    live: 'IRL',
    retry: 'Run it back',
    noSource: "Ain't no source for this, chief.",
    noData: "It's giving nothing right now.",
    platformApple: 'Apple Pods',
    platformSpotify: 'Spotify Pods',
    platformYoutube: 'YT Pods',
    platformOrfSound: 'ORF Sound Pods',
    platformRaiPlaySound: 'RaiPlay Sound Pods',
    platformSrfAudio: 'SRF Audio Pods',
    platformDrLyd: 'DR LYD Pods',
    platformRtbfAuvio: 'RTBF Auvio Pods',
    platformRneAudio: 'RNE Audio Pods',
    platformNpoLuister: 'NPO Luister Pods',
    platformSoundOn: 'SoundOn Pods',
    platformKkbox: 'KKBOX Pods',
    platformPodplay: 'Podplay Pods',
    platformSnipd: 'Snipd Pods',
    platformAudible: 'Audible Pods',
    platformIheartRadio: 'iHeartRadio Pods',
    platformSiriusxm: 'SiriusXM Pods',
    platformPandora: 'Pandora Pods',
    platformPodcastApp: 'Pod App Pods',
    platformRtlPlus: 'RTL+ Pods',
    platformTuneIn: 'TuneIn Pods',
    platformXimalaya: 'Ximalaya Pods',
    platformBilibili: 'BiliBili Pods',
    platformBbcSounds: 'BBC Sounds Pods',
    platformRadionet: 'radio.net Pods',
    platformAbclisten: 'ABC listen Pods',
    platformNrk: 'NRK Radio Pods',
    platformYleAreena: 'Yle Areena Pods',
    platformSverigesRadio: 'Sveriges Radio Pods',
    platformCastbox: 'Castbox Pods',
    platformPocketcasts: 'Pocket Casts Pods',
    platformAmazonmusic: 'Amazon Music Pods',
    platformPodbbang: 'podbbang Pods',
    platformAudioclip: 'audioclip Pods',
    platformArdsounds: 'ARD Sounds',
    platformRadiofrance: 'Radio France',
    platformDeezer: 'Deezer Pods',
    platformPodimo: 'Podimo Pods',
    platformPodcastAddict: 'Pod Addict Pods',
    platformRadiko: 'radiko Pods',
    platformIvoox: 'iVoox Pods',
    platformAll: 'Every Platform',
    topPodcasts: 'Goated Pods',
    topEpisodes: 'Goated Eps',
    typeTrending: 'Popping Off Pods',
    typeArts: 'Artsy Vibes',
    typeBusiness: 'Hustle Culture',
    typeComedy: "I'm Dead",
    typeEducation: 'Brain Gains',
    typeFiction: 'Made Up Lore',
    typeHealthFitness: 'Gym Bro & Wellness',
    typeHistory: 'Ancient Lore',
    typeLeisure: 'Chilling',
    typeMusic: 'Bops & Bangers',
    typeNews: 'The Tea',
    typeReligionSpirituality: 'Holy Vibes',
    typeScience: 'Nerd Stuff',
    typeSocietyCulture: 'Touch Grass',
    typeSports: 'Sportsball',
    typeTechnology: 'Tech Bro Vibes',
    typeTrueCrime: 'Sus AF',
    typeTvFilm: 'Bingeing',
    typeTopSubscriberShows: 'Top Sub Shows',
    typeTopSubscriberChannels: 'Top Sub Channels',
    typeBooks: 'BookTok',
    typeDesign: 'Aesthetics',
    typeFashionBeauty: 'Fits & Glam',
    typeFood: 'Eats',
    typePerformingArts: 'Theater Kid Energy',
    typeVisualArts: 'Visuals',
    typeCareers: '9 to 5 Grind',
    typeEntrepreneurship: 'CEO Mindset',
    typeInvesting: 'Stonks',
    typeManagement: 'Bossing Up',
    typeMarketing: 'Clout Chasing',
    typeNonProfit: 'Doing Good',
    typeComedyInterviews: 'Funny Yapping',
    typeImprov: 'Winging It',
    typeStandUp: 'Stand-Up',
    typeCourses: 'Classes',
    typeHowTo: 'Tutorials',
    typeLanguageLearning: 'Duolingo Vibes',
    typeSelfImprovement: 'Glow Up',
    typeComedyFiction: 'Funny Lore',
    typeDrama: 'The Drama',
    typeScienceFiction: 'Sci-Fi',
    typeGovernment: 'Gov Stuff',
    typeAlternativeHealth: 'Alt Wellness',
    typeFitness: 'Gains',
    typeMedicine: 'Med Stuff',
    typeMentalHealth: 'Mental Health Check',
    typeNutrition: 'Macros',
    typeSexuality: 'Spicy Talk',
    typeKidsFamily: 'Fam & Kiddos',
    typeEducationForKids: 'Brain Gains for Kids',
    typeParenting: 'Raising Crotch Goblins',
    typePetsAnimals: 'Fur Babies',
    typeStoriesForKids: 'Kid Lore',
    typeAnimationManga: 'Weeb Stuff',
    typeAutomotive: 'Car Bros',
    typeAviation: 'Plane Geeks',
    typeCrafts: 'DIYs',
    typeGames: 'Tabletop',
    typeHobbies: 'Side Quests',
    typeHomeGarden: 'Plant Parent Vibes',
    typeVideoGames: 'Gaming',
    typeMusicCommentary: 'Music Takes',
    typeMusicHistory: 'Music Lore',
    typeMusicInterviews: 'Artist Yapping',
    typeBusinessNews: 'Money Tea',
    typeDailyNews: 'Daily Tea',
    typeEntertainmentNews: 'Pop Culture Tea',
    typeNewsCommentary: 'Hot Takes',
    typePolitics: 'Politi-tea',
    typeSportsNews: 'Sports Tea',
    typeTechNews: 'Tech Tea',
    typeBuddhism: 'Buddhism',
    typeChristianity: 'Christianity',
    typeHinduism: 'Hinduism',
    typeIslam: 'Islam',
    typeJudaism: 'Judaism',
    typeReligion: 'Religion',
    typeSpirituality: 'Spiritual Vibes',
    typeAstronomy: 'Space Stuff',
    typeChemistry: 'Chem',
    typeEarthSciences: 'Earth Stuff',
    typeLifeSciences: 'Bio Stuff',
    typeMathematics: 'Math',
    typeNaturalSciences: 'Nature Science',
    typeNature: 'Touching Grass',
    typePhysics: 'Physics',
    typeSocialSciences: 'Social Science',
    typeDocumentary: 'Docs',
    typePersonalJournals: 'Trauma Dumping',
    typePhilosophy: 'Deep Thoughts',
    typePlacesTravel: 'Wanderlust',
    typeRelationships: 'Situationships',
    typeBaseball: 'Baseball',
    typeBasketball: 'Hoops',
    typeCricket: 'Cricket',
    typeFantasySports: 'Fantasy Sports',
    typeFootball: 'Football',
    typeGolf: 'Golf',
    typeHockey: 'Hockey',
    typeRugby: 'Rugby',
    typeRunning: 'Running',
    typeSoccer: 'Soccer',
    typeSwimming: 'Swimming',
    typeTennis: 'Tennis',
    typeVolleyball: 'Volleyball',
    typeWilderness: 'The Wild',
    typeWrestling: 'Wrestling',
    typeAfterShows: 'Post-Binge Yapping',
    typeFilmHistory: 'Movie Lore',
    typeFilmInterviews: 'Movie Yapping',
    typeFilmReviews: 'Movie Takes',
    typeTvReviews: 'TV Takes',
    periodLabel: 'Era',
    periodDaily: 'Daily',
    periodWeek: 'Weekly',
    periodMonth: 'Monthly',
    periodYear: 'Yearly',
    periodAll: 'All-time GOAT',
    allPlatform: 'Every Platform',
    languageChart: 'Lingo Chart',
    'scope.country': 'Lingo Chart',
    'scope.myPodcasts': 'My Pods',
    'scope.lang-en': 'English Pods',
    'scope.lang-zh': 'Chinese Pods',
    'scope.lang-es': 'Spanish Pods',
    'scope.lang-ar': 'Arabic Pods',
    'scope.lang-fr': 'French Pods',
    'scope.lang-pt': 'Portuguese Pods',
    'scope.lang-de': 'German Pods',
    'scope.lang-nl': 'Dutch Pods',
    dateLabel: 'Date',
    dateLatest: 'Freshest',
    reminderNeedToday: "No snapshot saved for today yet. Check today's chart and vibe check it.",
    reminderSavedToday: "Today's snapshot is locked in.",
    myPodcasts: 'My Pods',
    podcastsWord: 'Pods',
    episodesWord: 'Eps',
    notesWord: 'Yaps',
    myPodcastsImportGroupLabel: 'My Pods',
    myPodcastsImportRss: 'RSS',
    myPodcastsImportYoutube: 'YT',
    myPodcastsImportApple: 'Apple',
    myPodcastsImportSpotify: 'Spotify',
    myPodcastsImportOpml: 'OPML',
    myPodcastsImportActionRss: 'RSS',
    myPodcastsImportActionYoutube: 'YT',
    myPodcastsImportActionApple: 'Apple',
    myPodcastsImportActionSpotify: 'Spotify',
    myPodcastsImportActionOpml: 'OPML',
    myPodcastsImportPlaceholderRss: 'RSS',
    myPodcastsImportPlaceholderYoutube: 'YT',
    myPodcastsImportPlaceholderApple: 'Apple',
    myPodcastsImportPlaceholderSpotify: 'Spotify',
    myPodcastsImportPickOpml: 'OPML',
    myPodcastsImportFailed: 'Big yikes, it flopped. Refresh and try again bestie.',
    note: 'Yap',
    closeNote: 'Kill yap',
    notePlaceholder: 'Drop your thoughts bestie...',
    noteSaved: 'Yap secured',
    noteDeleted: 'Yap yeeted',
    noteEmptyExport: 'Drop a yap first',
    noteUnsaved: 'Unsaved vibes',
    noteSaving: 'Cooking...',
    noteDone: 'Bet',
    noteDelete: 'Yeet',
    noteSave: 'Lock in',
    noteDownload: 'Grab it',
    noteDownloadMd: 'Markdown (.md)',
    noteDownloadTxt: 'Text (.txt)',
    noteCopy: 'Snag',
    noteCopied: 'Yap snagged',
    noteLastSaved: 'Last locked in',
    noteNew: 'No yaps yet',
    noteFor: 'Yap for',
    noteDownloaded: 'Secured',
    close: 'Kill',
    previous: 'Back',
    next: 'Next',
    playlist: 'Playlist',
    playlistMode: 'Playlist Mode',
    refreshPlayer: 'Vibe check player',
    sponsored: '#Ad',
    ximalayaStoryPodcasts: 'Story Pods',
    ximalayaOpinionPodcasts: 'Hot Take Pods',
    'runtime.fallbackPodcast': 'Pod',
    'runtime.fallbackPodcasts': 'Pods',
    'runtime.youtubeFallbackTitlePlaylist': 'YT Playlist',
    'runtime.youtubeFallbackTitleVideo': 'YT Vid',
    'runtime.youtubeFallbackTitleChannel': 'YT Channel',
    'runtime.youtubeFallbackPublisher': 'YT',
    'runtime.appleBrandLabel': 'Apple Pods',
    'runtime.spotifyBrandLabel': 'Spotify',
    'runtime.applePodcastChannels': 'Apple Pod Channels'
  };

  const linkedinbroUiText = {
    language: 'Core Competency Dialect',
    searchPlaceholder: 'Discover thought leaders / masterclasses',
    clearSearch: 'Pivot strategy',
    surprise: 'Disrupt my feed',
    share: 'Amplify to network',
    refresh: 'Circle back',
    empty: 'Zero synergies found for these KPIs.',
    backToTop: 'Ascend the corporate ladder',
    open: 'Unpack',
    copyLink: 'Leverage URL',
    linkCopied: 'URL synergized',
    copyTitle: 'Leverage headline',
    titleCopied: 'Headline synergized',
    playEpisode: 'Execute deliverable',
    closePlayer: 'Sunset player',
    history: 'Track record',
    closeHistory: 'Archive track record',
    favorite: 'Value-add',
    unfavorite: 'Deprioritize',
    favoriteAdded: 'Onboarded to portfolio',
    favoriteRemoved: 'Offboarded',
    rankUpdateTitle: 'KPI performance update',
    loadFailedRefresh: 'Bandwidth issue. Please circle back and try again.',
    loadingDots: 'Aligning synergies...',
    loadingData: 'Crunching the analytics...',
    refreshingData: 'Pivoting the metrics...',
    ready: 'Optimized',
    cache: 'Knowledge base',
    cached: 'Archived for impact',
    refreshing: 'Circling back',
    loading: 'Onboarding',
    live: 'Real-time engagement',
    retry: 'Iterate',
    noSource: 'No deliverables found in this vertical.',
    noData: 'No actionable insights at this time.',
    platformApple: 'Apple Thought Leadership',
    platformSpotify: 'Spotify Masterclasses',
    platformYoutube: 'YouTube Synergies',
    platformOrfSound: 'ORF Sound Podcasts',
    platformRaiPlaySound: 'RaiPlay Sound Podcasts',
    platformSrfAudio: 'SRF Audio Podcasts',
    platformDrLyd: 'DR LYD Podcasts',
    platformRtbfAuvio: 'RTBF Auvio Podcasts',
    platformRneAudio: 'RNE Audio Podcasts',
    platformNpoLuister: 'NPO Luister Podcasts',
    platformSoundOn: 'SoundOn Podcasts',
    platformKkbox: 'KKBOX Podcasts',
    platformPodplay: 'Podplay Podcasts',
    platformSnipd: 'Snipd Podcasts',
    platformAudible: 'Audible Thought Leadership',
    platformIheartRadio: 'iHeartRadio Synergies',
    platformSiriusxm: 'SiriusXM Masterclasses',
    platformPandora: 'Pandora Thought Leadership',
    platformPodcastApp: 'Podcast App Ecosystem',
    platformRtlPlus: 'RTL+ Network',
    platformTuneIn: 'TuneIn Synergies',
    platformXimalaya: 'Ximalaya Ecosystem',
    platformBilibili: 'BiliBili Network',
    platformBbcSounds: 'BBC Sounds Ecosystem',
    platformRadionet: 'radio.net Network',
    platformAbclisten: 'ABC listen Ecosystem',
    platformNrk: 'NRK Radio Network',
    platformYleAreena: 'Yle Areena Ecosystem',
    platformSverigesRadio: 'Sveriges Radio Network',
    platformCastbox: 'Castbox Ecosystem',
    platformPocketcasts: 'Pocket Casts Network',
    platformAmazonmusic: 'Amazon Music Synergies',
    platformPodbbang: 'podbbang Ecosystem',
    platformAudioclip: 'audioclip Network',
    platformArdsounds: 'ARD Sounds',
    platformRadiofrance: 'Radio France',
    platformDeezer: 'Deezer Ecosystem',
    platformPodimo: 'Podimo Network',
    platformPodcastAddict: 'Podcast Addict Ecosystem',
    platformRadiko: 'radiko Network',
    platformIvoox: 'iVoox Ecosystem',
    platformAll: 'Entire Ecosystem',
    topPodcasts: 'Top Tier Thought Leadership',
    topEpisodes: 'High-Impact Masterclasses',
    typeTrending: 'Viral Synergies',
    typeArts: 'Creative Capital',
    typeBusiness: 'B2B & Enterprise',
    typeComedy: 'Corporate Humor',
    typeEducation: 'Upskilling & L&D',
    typeFiction: 'Scenario Planning',
    typeHealthFitness: 'Corporate Wellness',
    typeHistory: 'Legacy Case Studies',
    typeLeisure: 'OOO (Out of Office)',
    typeMusic: 'Audio Branding',
    typeNews: 'Industry Updates',
    typeReligionSpirituality: 'Mindfulness & Core Values',
    typeScience: 'R&D',
    typeSocietyCulture: 'Company Culture',
    typeSports: 'Team Building',
    typeTechnology: 'Tech Stack & Innovation',
    typeTrueCrime: 'Compliance & Risk Management',
    typeTvFilm: 'Media & PR',
    typeTopSubscriberShows: 'Premium Stakeholder Shows',
    typeTopSubscriberChannels: 'Premium Stakeholder Channels',
    typeBooks: 'Professional Development Literature',
    typeDesign: 'UX/UI & Design Thinking',
    typeFashionBeauty: 'Personal Branding',
    typeFood: 'Client Dinners',
    typePerformingArts: 'Keynote Speaking',
    typeVisualArts: 'Infographics & Data Viz',
    typeCareers: 'Career Trajectory',
    typeEntrepreneurship: 'Founder Journeys',
    typeInvesting: 'ROI & Capital Allocation',
    typeManagement: 'Leadership & Agile Management',
    typeMarketing: 'Growth Hacking & GTM',
    typeNonProfit: 'CSR & Impact',
    typeComedyInterviews: 'Fireside Chats',
    typeImprov: 'Agile Responses',
    typeStandUp: 'Keynote Speaking',
    typeCourses: 'Certifications',
    typeHowTo: 'Best Practices',
    typeLanguageLearning: 'Global Market Expansion',
    typeSelfImprovement: 'Continuous Optimization',
    typeComedyFiction: 'Lighthearted Scenarios',
    typeDrama: 'Stakeholder Conflict',
    typeScienceFiction: 'Future-Proofing',
    typeGovernment: 'Public Sector & Regulatory',
    typeAlternativeHealth: 'Holistic Wellness',
    typeFitness: 'Peak Performance',
    typeMedicine: 'Healthcare Verticals',
    typeMentalHealth: 'Burnout Prevention',
    typeNutrition: 'Fuel for Productivity',
    typeSexuality: 'DEI & Belonging',
    typeKidsFamily: 'Work-Life Integration',
    typeEducationForKids: 'Next-Gen Upskilling',
    typeParenting: 'Mentorship',
    typePetsAnimals: 'Office Pets',
    typeStoriesForKids: 'Junior Case Studies',
    typeAnimationManga: 'Visual Storytelling',
    typeAutomotive: 'Mobility Solutions',
    typeAviation: 'Aerospace Verticals',
    typeCrafts: 'Maker Culture',
    typeGames: 'Gamification',
    typeHobbies: 'Passion Projects',
    typeHomeGarden: 'WFH Environment',
    typeVideoGames: 'Interactive Media',
    typeMusicCommentary: 'Audio Branding Analysis',
    typeMusicHistory: 'Legacy Audio',
    typeMusicInterviews: 'Audio Fireside Chats',
    typeBusinessNews: 'Market Movers',
    typeDailyNews: 'Daily Standup',
    typeEntertainmentNews: 'PR Updates',
    typeNewsCommentary: 'Thought Leader Takes',
    typePolitics: 'Policy & Regulation',
    typeSportsNews: 'Team Building Updates',
    typeTechNews: 'Disruption Updates',
    typeBuddhism: 'Zen Leadership',
    typeChristianity: 'Faith-Based Leadership',
    typeHinduism: 'Dharmic Leadership',
    typeIslam: 'Halal Business Practices',
    typeJudaism: 'Kosher Networking',
    typeReligion: 'Core Belief Systems',
    typeSpirituality: 'Purpose-Driven Work',
    typeAstronomy: 'Moonshot Thinking',
    typeChemistry: 'Team Synergy',
    typeEarthSciences: 'Sustainability & ESG',
    typeLifeSciences: 'BioTech Verticals',
    typeMathematics: 'Quantitative Analysis',
    typeNaturalSciences: 'Environmental Impact',
    typeNature: 'Green Initiatives',
    typePhysics: 'First Principles Thinking',
    typeSocialSciences: 'Behavioral Economics',
    typeDocumentary: 'Deep Dive Case Studies',
    typePersonalJournals: 'Founder Diaries',
    typePhilosophy: 'Core Paradigms',
    typePlacesTravel: 'Digital Nomadism',
    typeRelationships: 'Stakeholder Management',
    typeBaseball: 'Hitting Home Runs',
    typeBasketball: 'Full Court Press',
    typeCricket: 'Long-Term Strategy',
    typeFantasySports: 'Predictive Analytics',
    typeFootball: 'Moving the Needle',
    typeGolf: 'Executive Networking',
    typeHockey: 'Skating to the Puck',
    typeRugby: 'Scrum Methodologies',
    typeRunning: 'Sprint Planning',
    typeSoccer: 'Global Synergies',
    typeSwimming: 'Deep Dives',
    typeTennis: 'One-on-One Networking',
    typeVolleyball: 'Cross-Functional Spikes',
    typeWilderness: 'Navigating Ambiguity',
    typeWrestling: 'Overcoming Pushback',
    typeAfterShows: 'Post-Mortems',
    typeFilmHistory: 'Legacy Media',
    typeFilmInterviews: 'Media Fireside Chats',
    typeFilmReviews: 'Media Audits',
    typeTvReviews: 'Broadcast Audits',
    periodLabel: 'Timeline',
    periodDaily: 'Daily Standup',
    periodWeek: 'Weekly Sync',
    periodMonth: 'Monthly Review',
    periodYear: 'Annual Review',
    periodAll: 'Lifetime Value',
    allPlatform: 'Entire Ecosystem',
    languageChart: 'Core Competency Matrix',
    'scope.country': 'Market Matrix',
    'scope.myPodcasts': 'My Personal Brand Portfolio',
    'scope.lang-en': 'English Thought Leadership',
    'scope.lang-zh': 'Chinese Thought Leadership',
    'scope.lang-es': 'Spanish Thought Leadership',
    'scope.lang-ar': 'Arabic Thought Leadership',
    'scope.lang-fr': 'French Thought Leadership',
    'scope.lang-pt': 'Portuguese Thought Leadership',
    'scope.lang-de': 'German Thought Leadership',
    'scope.lang-nl': 'Dutch Thought Leadership',
    dateLabel: 'Timestamp',
    dateLatest: 'Bleeding Edge',
    reminderNeedToday: "No analytics snapshot saved for today yet. Audit today's matrix and circle back.",
    reminderSavedToday: "Today's analytics snapshot has been securely archived.",
    myPodcasts: 'My Personal Brand Portfolio',
    podcastsWord: 'Thought Leadership',
    episodesWord: 'Masterclasses',
    notesWord: 'Action Items',
    myPodcastsImportGroupLabel: 'My Personal Brand Portfolio',
    myPodcastsImportRss: 'RSS Feed',
    myPodcastsImportYoutube: 'YouTube',
    myPodcastsImportApple: 'Apple',
    myPodcastsImportSpotify: 'Spotify',
    myPodcastsImportOpml: 'OPML',
    myPodcastsImportActionRss: 'RSS',
    myPodcastsImportActionYoutube: 'YouTube',
    myPodcastsImportActionApple: 'Apple',
    myPodcastsImportActionSpotify: 'Spotify',
    myPodcastsImportActionOpml: 'OPML',
    myPodcastsImportPlaceholderRss: 'RSS',
    myPodcastsImportPlaceholderYoutube: 'YouTube',
    myPodcastsImportPlaceholderApple: 'Apple',
    myPodcastsImportPlaceholderSpotify: 'Spotify',
    myPodcastsImportPickOpml: 'OPML',
    myPodcastsImportFailed: 'Bandwidth issue. Please circle back and try again.',
    note: 'Action Item',
    closeNote: 'Sunset action item',
    notePlaceholder: 'Document your key takeaways here...',
    noteSaved: 'Action item archived',
    noteDeleted: 'Action item deprioritized',
    noteEmptyExport: 'Document a key takeaway first',
    noteUnsaved: 'Uncommitted deliverables',
    noteSaving: 'Committing to cloud...',
    noteDone: 'Executed',
    noteDelete: 'Deprioritize',
    noteSave: 'Archive',
    noteDownload: 'Export Deliverable',
    noteDownloadMd: 'Markdown (.md)',
    noteDownloadTxt: 'Plain Text (.txt)',
    noteCopy: 'Duplicate Asset',
    noteCopied: 'Asset Duplicated',
    noteLastSaved: 'Last archived',
    noteNew: 'No action items logged yet',
    noteFor: 'Action Item For',
    noteDownloaded: 'Deliverable exported',
    close: 'Sunset',
    previous: 'Circle Back',
    next: 'Fast Forward',
    playlist: 'Content Pipeline',
    playlistMode: 'Pipeline Mode',
    refreshPlayer: 'Circle back on player',
    sponsored: 'Strategic Partnership',
    ximalayaStoryPodcasts: 'Narrative Thought Leadership',
    ximalayaOpinionPodcasts: 'Thought Leader Takes',
    'runtime.fallbackPodcast': 'Thought Leadership Asset',
    'runtime.fallbackPodcasts': 'Thought Leadership Assets',
    'runtime.youtubeFallbackTitlePlaylist': 'YouTube Content Pipeline',
    'runtime.youtubeFallbackTitleVideo': 'YouTube Deliverable',
    'runtime.youtubeFallbackTitleChannel': 'YouTube Brand Channel',
    'runtime.youtubeFallbackPublisher': 'YouTube',
    'runtime.appleBrandLabel': 'Apple Thought Leadership',
    'runtime.spotifyBrandLabel': 'Spotify',
    'runtime.applePodcastChannels': 'Apple Premium Networks'
  };

  window.ENGLISH_TEXT_MODES = Object.assign({}, window.ENGLISH_TEXT_MODES, {
    genz: {
      uiText: genzUiText
    },
    linkedinbro: {
      uiText: linkedinbroUiText
    }
  });
}());
