const utils = {
    translations: {
        en: {
            siteName: 'Currency Converter | Currency Calculator',
            siteDescription: 'Smart Currency Converter',
            lastUpdated: 'Last Updated: ',
            searchPlaceholder: 'Search currencies...',
            starredCurrencies: '⭐ Starred Currencies',
            allCurrencies: 'All Currencies',
            inputPlaceholder: 'Enter amounts (e.g., 100;200;300)\nSupport calculations (e.g., 100*2)',
            errorFetching: 'Error fetching data',
            noData: 'No data available',
            currencies: {
                AED: "UAE Dirham",
                AFN: "Afghan Afghani",
                ALL: "Albanian Lek",
                AMD: "Armenian Dram",
                ANG: "Netherlands Antillean Guilder",
                AOA: "Angolan Kwanza",
                ARS: "Argentine Peso",
                AUD: "Australian Dollar",
                AWG: "Aruban Florin",
                AZN: "Azerbaijani Manat",
                BAM: "Bosnia-Herzegovina Mark",
                BBD: "Barbadian Dollar",
                BDT: "Bangladeshi Taka",
                BGN: "Bulgarian Lev",
                BHD: "Bahraini Dinar",
                BIF: "Burundian Franc",
                BMD: "Bermudian Dollar",
                BND: "Brunei Dollar",
                BOB: "Bolivian Boliviano",
                BRL: "Brazilian Real",
                BSD: "Bahamian Dollar",
                BTN: "Bhutanese Ngultrum",
                BWP: "Botswanan Pula",
                BYN: "Belarusian Ruble",
                BZD: "Belize Dollar",
                CAD: "Canadian Dollar",
                CDF: "Congolese Franc",
                CHF: "Swiss Franc",
                CLP: "Chilean Peso",
                CNY: "Chinese Yuan",
                COP: "Colombian Peso",
                CRC: "Costa Rican Colón",
                CUP: "Cuban Peso",
                CVE: "Cape Verdean Escudo",
                CZK: "Czech Koruna",
                DJF: "Djiboutian Franc",
                DKK: "Danish Krone",
                DOP: "Dominican Peso",
                DZD: "Algerian Dinar",
                EGP: "Egyptian Pound",
                ERN: "Eritrean Nakfa",
                ETB: "Ethiopian Birr",
                EUR: "Euro",
                FJD: "Fijian Dollar",
                FKP: "Falkland Islands Pound",
                GBP: "British Pound",
                GEL: "Georgian Lari",
                GHS: "Ghanaian Cedi",
                GIP: "Gibraltar Pound",
                GMD: "Gambian Dalasi",
                GNF: "Guinean Franc",
                GTQ: "Guatemalan Quetzal",
                GYD: "Guyanaese Dollar",
                HKD: "Hong Kong Dollar",
                HNL: "Honduran Lempira",
                HRK: "Croatian Kuna",
                HTG: "Haitian Gourde",
                HUF: "Hungarian Forint",
                IDR: "Indonesian Rupiah",
                ILS: "Israeli New Shekel",
                INR: "Indian Rupee",
                IQD: "Iraqi Dinar",
                IRR: "Iranian Rial",
                ISK: "Icelandic Króna",
                JMD: "Jamaican Dollar",
                JOD: "Jordanian Dinar",
                JPY: "Japanese Yen",
                KES: "Kenyan Shilling",
                KGS: "Kyrgystani Som",
                KHR: "Cambodian Riel",
                KMF: "Comorian Franc",
                KPW: "North Korean Won",
                KRW: "South Korean Won",
                KWD: "Kuwaiti Dinar",
                KYD: "Cayman Islands Dollar",
                KZT: "Kazakhstani Tenge",
                LAK: "Laotian Kip",
                LBP: "Lebanese Pound",
                LKR: "Sri Lankan Rupee",
                LRD: "Liberian Dollar",
                LSL: "Lesotho Loti",
                LYD: "Libyan Dinar",
                MAD: "Moroccan Dirham",
                MDL: "Moldovan Leu",
                MGA: "Malagasy Ariary",
                MKD: "Macedonian Denar",
                MMK: "Myanmar Kyat",
                MNT: "Mongolian Tugrik",
                MOP: "Macanese Pataca",
                MRU: "Mauritanian Ouguiya",
                MUR: "Mauritian Rupee",
                MVR: "Maldivian Rufiyaa",
                MWK: "Malawian Kwacha",
                MXN: "Mexican Peso",
                MYR: "Malaysian Ringgit",
                MZN: "Mozambican Metical",
                NAD: "Namibian Dollar",
                NGN: "Nigerian Naira",
                NIO: "Nicaraguan Córdoba",
                NOK: "Norwegian Krone",
                NPR: "Nepalese Rupee",
                NZD: "New Zealand Dollar",
                OMR: "Omani Rial",
                PAB: "Panamanian Balboa",
                PEN: "Peruvian Sol",
                PGK: "Papua New Guinean Kina",
                PHP: "Philippine Peso",
                PKR: "Pakistani Rupee",
                PLN: "Polish Złoty",
                PYG: "Paraguayan Guarani",
                QAR: "Qatari Rial",
                RON: "Romanian Leu",
                RSD: "Serbian Dinar",
                RUB: "Russian Ruble",
                RWF: "Rwandan Franc",
                SAR: "Saudi Riyal",
                SBD: "Solomon Islands Dollar",
                SCR: "Seychellois Rupee",
                SDG: "Sudanese Pound",
                SEK: "Swedish Krona",
                SGD: "Singapore Dollar",
                SHP: "Saint Helena Pound",
                SLL: "Sierra Leonean Leone",
                SOS: "Somali Shilling",
                SRD: "Surinamese Dollar",
                SSP: "South Sudanese Pound",
                STN: "São Tomé and Príncipe Dobra",
                SVC: "Salvadoran Colón",
                SYP: "Syrian Pound",
                SZL: "Swazi Lilangeni",
                THB: "Thai Baht",
                TJS: "Tajikistani Somoni",
                TMT: "Turkmenistani Manat",
                TND: "Tunisian Dinar",
                TOP: "Tongan Paʻanga",
                TRY: "Turkish Lira",
                TTD: "Trinidad and Tobago Dollar",
                TWD: "New Taiwan Dollar",
                TZS: "Tanzanian Shilling",
                UAH: "Ukrainian Hryvnia",
                UGX: "Ugandan Shilling",
                USD: "US Dollar",
                UYU: "Uruguayan Peso",
                UZS: "Uzbekistani Som",
                VES: "Venezuelan Bolívar",
                VND: "Vietnamese Dong",
                VUV: "Vanuatu Vatu",
                WST: "Samoan Tala",
                XAF: "Central African CFA Franc",
                XCD: "East Caribbean Dollar",
                XDR: "Special Drawing Rights",
                XOF: "West African CFA Franc",
                XPF: "CFP Franc",
                YER: "Yemeni Rial",
                ZAR: "South African Rand",
                ZMW: "Zambian Kwacha",
                ZWL: "Zimbabwean Dollar"
            }
        },
        'zh-Hans': {
            siteName: 'ExchangeWise 汇率转换',
            siteDescription: '智能货币转换器',
            lastUpdated: '最后更新：',
            searchPlaceholder: '搜索货币...',
            starredCurrencies: '⭐ 已收藏货币',
            allCurrencies: '所有货币',
            inputPlaceholder: '输入金额（例如：100;200;300）\n支持计算（例如：100*2）',
            errorFetching: '获取数据失败',
            noData: '暂无数据',
            currencies: {
                USD: "美元",
                EUR: "欧元",
                GBP: "英镑"
            }
        }
    },

    currencyMeta: {
        "1INCH": { symbol: '₿', emoji: '🪙' },
        AAVE: { symbol: '₿', emoji: '🪙' },
        ADA: { symbol: '₿', emoji: '🪙' },
        AED: { symbol: 'د.إ', emoji: '🇦🇪' },
        AFN: { symbol: '؋', emoji: '🇦🇫' },
        AGIX: { symbol: '₿', emoji: '🪙' },
        AKT: { symbol: '₿', emoji: '🪙' },
        ALGO: { symbol: '₿', emoji: '🪙' },
        ALL: { symbol: 'L', emoji: '🇦🇱' },
        AMD: { symbol: '֏', emoji: '🇦🇲' },
        AMP: { symbol: '₿', emoji: '🪙' },
        ANG: { symbol: 'ƒ', emoji: '🇳🇱' },
        AOA: { symbol: 'Kz', emoji: '🇦🇴' },
        APE: { symbol: '₿', emoji: '🪙' },
        APT: { symbol: '₿', emoji: '🪙' },
        AR: { symbol: '₿', emoji: '🪙' },
        ARB: { symbol: '₿', emoji: '🪙' },
        ARS: { symbol: '$', emoji: '🇦🇷' },
        ATOM: { symbol: '₿', emoji: '🪙' },
        ATS: { symbol: 'öS', emoji: '🇦🇹' },
        AUD: { symbol: 'A$', emoji: '🇦🇺' },
        AVAX: { symbol: '₿', emoji: '🪙' },
        AWG: { symbol: 'ƒ', emoji: '🇦🇼' },
        AXS: { symbol: '₿', emoji: '🪙' },
        AZM: { symbol: '₼', emoji: '🇦🇿' },
        AZN: { symbol: '₼', emoji: '🇦🇿' },
        BAKE: { symbol: '₿', emoji: '🪙' },
        BAM: { symbol: 'KM', emoji: '🇧🇦' },
        BAT: { symbol: '₿', emoji: '🪙' },
        BBD: { symbol: '$', emoji: '🇧🇧' },
        BCH: { symbol: '₿', emoji: '🪙' },
        BDT: { symbol: '৳', emoji: '🇧🇩' },
        BEF: { symbol: 'Fr', emoji: '🇧🇪' },
        BGN: { symbol: 'лв', emoji: '🇧🇬' },
        BHD: { symbol: '.د.ب', emoji: '🇧🇭' },
        BIF: { symbol: 'Fr', emoji: '🇧🇮' },
        BMD: { symbol: '$', emoji: '🇧🇲' },
        BNB: { symbol: '₿', emoji: '🪙' },
        BND: { symbol: '$', emoji: '🇧🇳' },
        BOB: { symbol: 'Bs.', emoji: '🇧🇴' },
        BRL: { symbol: 'R$', emoji: '🇧🇷' },
        BSD: { symbol: '$', emoji: '🇧🇸' },
        BSV: { symbol: '₿', emoji: '🪙' },
        BSW: { symbol: '₿', emoji: '🪙' },
        BTC: { symbol: '₿', emoji: '🪙' },
        BTCB: { symbol: '₿', emoji: '🪙' },
        BTG: { symbol: '₿', emoji: '🪙' },
        BTN: { symbol: 'Nu.', emoji: '🇧🇹' },
        BTT: { symbol: '₿', emoji: '🪙' },
        BUSD: { symbol: '₿', emoji: '🪙' },
        BWP: { symbol: 'P', emoji: '🇧🇼' },
        BYN: { symbol: 'Br', emoji: '🇧🇾' },
        BYR: { symbol: 'Br', emoji: '🇧🇾' },
        BZD: { symbol: '$', emoji: '🇧🇿' },
        CAD: { symbol: 'C$', emoji: '🇨🇦' },
        CAKE: { symbol: '₿', emoji: '🪙' },
        CDF: { symbol: 'Fr', emoji: '🇨🇩' },
        CELO: { symbol: '₿', emoji: '🪙' },
        CFX: { symbol: '₿', emoji: '🪙' },
        CHF: { symbol: 'Fr', emoji: '🇨🇭' },
        CHZ: { symbol: '₿', emoji: '🪙' },
        CLP: { symbol: '$', emoji: '🇨🇱' },
        CNH: { symbol: '¥', emoji: '🇨🇳' },
        CNY: { symbol: '¥', emoji: '🇨🇳' },
        COMP: { symbol: '₿', emoji: '🪙' },
        COP: { symbol: '$', emoji: '🇨🇴' },
        CRC: { symbol: '₡', emoji: '🇨🇷' },
        CRO: { symbol: '₿', emoji: '🪙' },
        CRV: { symbol: '₿', emoji: '🪙' },
        CSPR: { symbol: '₿', emoji: '🪙' },
        CUC: { symbol: '$', emoji: '🇨🇺' },
        CUP: { symbol: '$', emoji: '🇨🇺' },
        CVE: { symbol: '$', emoji: '🇨🇻' },
        CVX: { symbol: '₿', emoji: '🪙' },
        CYP: { symbol: '£', emoji: '🇨🇾' },
        CZK: { symbol: 'Kč', emoji: '🇨🇿' },
        DAI: { symbol: '₿', emoji: '🪙' },
        DASH: { symbol: '₿', emoji: '🪙' },
        DCR: { symbol: '₿', emoji: '🪙' },
        DEM: { symbol: 'DM', emoji: '🇩🇪' },
        DFI: { symbol: '₿', emoji: '🪙' },
        DJF: { symbol: 'Fr', emoji: '🇩🇯' },
        DKK: { symbol: 'kr', emoji: '🇩🇰' },
        DOGE: { symbol: '₿', emoji: '🪙' },
        DOP: { symbol: '$', emoji: '🇩🇴' },
        DOT: { symbol: '₿', emoji: '🪙' },
        DYDX: { symbol: '₿', emoji: '🪙' },
        DZD: { symbol: 'د.ج', emoji: '🇩🇿' },
        EEK: { symbol: 'kr', emoji: '🇪🇪' },
        EGLD: { symbol: '₿', emoji: '🪙' },
        EGP: { symbol: '£', emoji: '🇪🇬' },
        ENJ: { symbol: '₿', emoji: '🪙' },
        EOS: { symbol: '₿', emoji: '🪙' },
        ERN: { symbol: 'Nfk', emoji: '🇪🇷' },
        ESP: { symbol: '₧', emoji: '🇪🇸' },
        ETB: { symbol: 'Br', emoji: '🇪🇹' },
        ETC: { symbol: '₿', emoji: '🪙' },
        ETH: { symbol: '₿', emoji: '🪙' },
        EUR: { symbol: '€', emoji: '🇪🇺' },
        FEI: { symbol: '₿', emoji: '🪙' },
        FIL: { symbol: '₿', emoji: '🪙' },
        FIM: { symbol: 'mk', emoji: '🇫🇮' },
        FJD: { symbol: '$', emoji: '🇫🇯' },
        FKP: { symbol: '£', emoji: '🇫🇰' },
        FLOW: { symbol: '₿', emoji: '🪙' },
        FLR: { symbol: '₿', emoji: '🪙' },
        FRAX: { symbol: '₿', emoji: '🪙' },
        FRF: { symbol: '₣', emoji: '🇫🇷' },
        FTM: { symbol: '₿', emoji: '🪙' },
        FTT: { symbol: '₿', emoji: '🪙' },
        FXS: { symbol: '₿', emoji: '🪙' },
        GALA: { symbol: '₿', emoji: '🪙' },
        GBP: { symbol: '£', emoji: '🇬🇧' },
        GEL: { symbol: '₾', emoji: '🇬🇪' },
        GGP: { symbol: '£', emoji: '🇬🇬' },
        GHC: { symbol: '₵', emoji: '🇬🇭' },
        GHS: { symbol: '₵', emoji: '🇬🇭' },
        GIP: { symbol: '£', emoji: '🇬🇮' },
        GMD: { symbol: 'D', emoji: '🇬🇲' },
        GMX: { symbol: '₿', emoji: '🪙' },
        GNF: { symbol: 'Fr', emoji: '🇬🇳' },
        GNO: { symbol: '₿', emoji: '🪙' },
        GRD: { symbol: '₯', emoji: '🇬🇷' },
        GRT: { symbol: '₿', emoji: '🪙' },
        GT: { symbol: '₿', emoji: '🪙' },
        GTQ: { symbol: 'Q', emoji: '🇬🇹' },
        GUSD: { symbol: '₿', emoji: '🪙' },
        GYD: { symbol: '$', emoji: '🇬🇾' },
        HBAR: { symbol: '₿', emoji: '🪙' },
        HKD: { symbol: 'HK$', emoji: '🇭🇰' },
        HNL: { symbol: 'L', emoji: '🇭🇳' },
        HNT: { symbol: '₿', emoji: '🪙' },
        HOT: { symbol: '₿', emoji: '🪙' },
        HRK: { symbol: 'kn', emoji: '🇭🇷' },
        HT: { symbol: '₿', emoji: '🪙' },
        HTG: { symbol: 'G', emoji: '🇭🇹' },
        HUF: { symbol: 'Ft', emoji: '🇭🇺' },
        ICP: { symbol: '₿', emoji: '🪙' },
        IDR: { symbol: 'Rp', emoji: '🇮🇩' },
        IEP: { symbol: '£', emoji: '🇮🇪' },
        ILS: { symbol: '₪', emoji: '🇮🇱' },
        IMP: { symbol: '£', emoji: '🇮🇲' },
        IMX: { symbol: '₿', emoji: '🪙' },
        INJ: { symbol: '₿', emoji: '🪙' },
        INR: { symbol: '₹', emoji: '🇮🇳' },
        IQD: { symbol: 'ع.د', emoji: '🇮🇶' },
        IRR: { symbol: '﷼', emoji: '🇮🇷' },
        ISK: { symbol: 'kr', emoji: '🇮🇸' },
        ITL: { symbol: '₤', emoji: '🇮🇹' },
        JEP: { symbol: '£', emoji: '🇯🇪' },
        JMD: { symbol: '$', emoji: '🇯🇲' },
        JOD: { symbol: 'د.ا', emoji: '🇯🇴' },
        JPY: { symbol: '¥', emoji: '🇯🇵' },
        KAS: { symbol: '₿', emoji: '🪙' },
        KAVA: { symbol: '₿', emoji: '🪙' },
        KCS: { symbol: '₿', emoji: '🪙' },
        KDA: { symbol: '₿', emoji: '🪙' },
        KES: { symbol: 'Sh', emoji: '🇰🇪' },
        KGS: { symbol: 'с', emoji: '🇰🇬' },
        KHR: { symbol: '៛', emoji: '🇰🇭' },
        KLAY: { symbol: '₿', emoji: '🪙' },
        KMF: { symbol: 'Fr', emoji: '🇰🇲' },
        KNC: { symbol: '₿', emoji: '🪙' },
        KPW: { symbol: '₩', emoji: '🇰🇵' },
        KRW: { symbol: '₩', emoji: '🇰🇷' },
        KSM: { symbol: '₿', emoji: '🪙' },
        KWD: { symbol: 'د.ك', emoji: '🇰🇼' },
        KYD: { symbol: '$', emoji: '🇰🇾' },
        KZT: { symbol: '₸', emoji: '🇰🇿' },
        LAK: { symbol: '₭', emoji: '🇱🇦' },
        LBP: { symbol: 'ل.ل', emoji: '🇱🇧' },
        LDO: { symbol: '₿', emoji: '🪙' },
        LEO: { symbol: '₿', emoji: '🪙' },
        LINK: { symbol: '₿', emoji: '🪙' },
        LKR: { symbol: '₨', emoji: '🇱🇰' },
        LRC: { symbol: '₿', emoji: '🪙' },
        LRD: { symbol: '$', emoji: '🇱🇷' },
        LSL: { symbol: 'L', emoji: '🇱🇸' },
        LTC: { symbol: '₿', emoji: '🪙' },
        LTL: { symbol: 'Lt', emoji: '🇱🇹' },
        LUF: { symbol: 'F', emoji: '🇱🇺' },
        LUNA: { symbol: '₿', emoji: '🪙' },
        LUNC: { symbol: '₿', emoji: '🪙' },
        LVL: { symbol: 'Ls', emoji: '🇱🇻' },
        LYD: { symbol: 'ل.د', emoji: '🇱🇾' },
        MAD: { symbol: 'د.م.', emoji: '🇲🇦' },
        MANA: { symbol: '₿', emoji: '🪙' },
        MATIC: { symbol: '₿', emoji: '🪙' },
        MBX: { symbol: '₿', emoji: '🪙' },
        MDL: { symbol: 'L', emoji: '🇲🇩' },
        MGA: { symbol: 'Ar', emoji: '🇲🇬' },
        MGF: { symbol: 'MG', emoji: '🇲🇬' },
        MINA: { symbol: '₿', emoji: '🪙' },
        MKD: { symbol: 'ден', emoji: '🇲🇰' },
        MKR: { symbol: '₿', emoji: '🪙' },
        MMK: { symbol: 'K', emoji: '🇲🇲' },
        MNT: { symbol: '₮', emoji: '🇲🇳' },
        MOP: { symbol: 'MOP$', emoji: '🇲🇴' },
        MRO: { symbol: 'UM', emoji: '🇲🇷' },
        MRU: { symbol: 'UM', emoji: '🇲🇷' },
        MTL: { symbol: 'Lm', emoji: '🇲🇹' },
        MUR: { symbol: '₨', emoji: '🇲🇺' },
        MVR: { symbol: 'Rf', emoji: '🇲🇻' },
        MWK: { symbol: 'MK', emoji: '🇲🇼' },
        MXN: { symbol: '$', emoji: '🇲🇽' },
        MXV: { symbol: 'UDI', emoji: '🇲🇽' },
        MYR: { symbol: 'RM', emoji: '🇲🇾' },
        MZM: { symbol: 'MT', emoji: '🇲🇿' },
        MZN: { symbol: 'MT', emoji: '🇲🇿' },
        NAD: { symbol: '$', emoji: '🇳🇦' },
        NEAR: { symbol: '₿', emoji: '🪙' },
        NEO: { symbol: '₿', emoji: '🪙' },
        NEXO: { symbol: '₿', emoji: '🪙' },
        NFT: { symbol: '₿', emoji: '🪙' },
        NGN: { symbol: '₦', emoji: '🇳🇬' },
        NIO: { symbol: 'C$', emoji: '🇳🇮' },
        NLG: { symbol: 'ƒ', emoji: '🇳🇱' },
        NOK: { symbol: 'kr', emoji: '🇳🇴' },
        NPR: { symbol: '₨', emoji: '🇳🇵' },
        NZD: { symbol: 'NZ$', emoji: '🇳🇿' },
        OKB: { symbol: '₿', emoji: '🪙' },
        OMR: { symbol: 'ر.ع.', emoji: '🇴🇲' },
        ONE: { symbol: '₿', emoji: '🪙' },
        OP: { symbol: '₿', emoji: '🪙' },
        ORDI: { symbol: '₿', emoji: '🪙' },
        PAB: { symbol: 'B/.', emoji: '🇵🇦' },
        PAXG: { symbol: '₿', emoji: '🪙' },
        PEN: { symbol: 'S/.', emoji: '🇵🇪' },
        PEPE: { symbol: '₿', emoji: '🪙' },
        PGK: { symbol: 'K', emoji: '🇵🇬' },
        PHP: { symbol: '₱', emoji: '🇵🇭' },
        PKR: { symbol: '₨', emoji: '🇵🇰' },
        PLN: { symbol: 'zł', emoji: '🇵🇱' },
        PTE: { symbol: '$', emoji: '🇵🇹' },
        PYG: { symbol: '₲', emoji: '🇵🇾' },
        QAR: { symbol: 'ر.ق', emoji: '🇶🇦' },
        QNT: { symbol: '₿', emoji: '🪙' },
        QTUM: { symbol: '₿', emoji: '🪙' },
        ROL: { symbol: 'L', emoji: '🇷🇴' },
        RON: { symbol: 'lei', emoji: '🇷🇴' },
        RPL: { symbol: '₿', emoji: '🪙' },
        RSD: { symbol: 'дин.', emoji: '🇷🇸' },
        RUB: { symbol: '₽', emoji: '🇷🇺' },
        RUNE: { symbol: '₿', emoji: '🪙' },
        RVN: { symbol: '₿', emoji: '🪙' },
        RWF: { symbol: 'Fr', emoji: '🇷🇼' },
        SAND: { symbol: '₿', emoji: '🪙' },
        SAR: { symbol: 'ر.س', emoji: '🇸🇦' },
        SBD: { symbol: '$', emoji: '🇸🇧' },
        SCR: { symbol: '₨', emoji: '🇸🇨' },
        SDD: { symbol: 'ج.س.', emoji: '🇸🇩' },
        SDG: { symbol: 'ج.س.', emoji: '🇸🇩' },
        SEK: { symbol: 'kr', emoji: '🇸🇪' },
        SGD: { symbol: 'S$', emoji: '🇸🇬' },
        SHIB: { symbol: '₿', emoji: '🪙' },
        SHP: { symbol: '£', emoji: '🇸🇭' },
        SIT: { symbol: 'SIT', emoji: '🇸🇮' },
        SKK: { symbol: 'Sk', emoji: '🇸🇰' },
        SLE: { symbol: 'Le', emoji: '🇸🇱' },
        SLL: { symbol: 'Le', emoji: '🇸🇱' },
        SNX: { symbol: '₿', emoji: '🪙' },
        SOL: { symbol: '₿', emoji: '🪙' },
        SOS: { symbol: 'Sh', emoji: '🇸🇴' },
        SPL: { symbol: '₿', emoji: '🪙' },
        SRD: { symbol: '$', emoji: '🇸🇷' },
        SRG: { symbol: 'Sf', emoji: '🇸🇷' },
        STD: { symbol: 'Db', emoji: '🇸🇹' },
        STN: { symbol: 'Db', emoji: '🇸🇹' },
        STX: { symbol: '₿', emoji: '🪙' },
        SUI: { symbol: '₿', emoji: '🪙' },
        SVC: { symbol: '₡', emoji: '🇸🇻' },
        SYP: { symbol: '£', emoji: '🇸🇾' },
        SZL: { symbol: 'L', emoji: '🇸🇿' },
        THB: { symbol: '฿', emoji: '🇹🇭' },
        THETA: { symbol: '₿', emoji: '🪙' },
        TJS: { symbol: 'ЅМ', emoji: '🇹🇯' },
        TMM: { symbol: 'm', emoji: '🇹🇲' },
        TMT: { symbol: 'm', emoji: '🇹🇲' },
        TND: { symbol: 'د.ت', emoji: '🇹🇳' },
        TON: { symbol: '₿', emoji: '🪙' },
        TOP: { symbol: 'T$', emoji: '🇹🇴' },
        TRL: { symbol: '₺', emoji: '🇹🇷' },
        TRX: { symbol: '₿', emoji: '🪙' },
        TRY: { symbol: '₺', emoji: '🇹🇷' },
        TTD: { symbol: '$', emoji: '🇹🇹' },
        TUSD: { symbol: '₿', emoji: '🪙' },
        TVD: { symbol: '$', emoji: '🇹🇻' },
        TWD: { symbol: 'NT$', emoji: '🇹🇼' },
        TWT: { symbol: '₿', emoji: '🪙' },
        TZS: { symbol: 'Sh', emoji: '🇹🇿' },
        UAH: { symbol: '₴', emoji: '🇺🇦' },
        UGX: { symbol: 'Sh', emoji: '🇺🇬' },
        UNI: { symbol: '₿', emoji: '🪙' },
        USD: { symbol: '$', emoji: '🇺🇸' },
        USDC: { symbol: '₿', emoji: '🪙' },
        USDD: { symbol: '₿', emoji: '🪙' },
        USDP: { symbol: '₿', emoji: '🪙' },
        USDT: { symbol: '₿', emoji: '🪙' },
        UYU: { symbol: '$', emoji: '🇺🇾' },
        UZS: { symbol: "so'm", emoji: '🇺🇿' },
        VAL: { symbol: '₤', emoji: '🇻🇦' },
        VEB: { symbol: 'Bs.', emoji: '🇻🇪' },
        VED: { symbol: 'Bs.', emoji: '🇻🇪' },
        VEF: { symbol: 'Bs.', emoji: '🇻🇪' },
        VES: { symbol: 'Bs.', emoji: '🇻🇪' },
        VET: { symbol: '₿', emoji: '🪙' },
        VND: { symbol: '₫', emoji: '🇻🇳' },
        VUV: { symbol: 'Vt', emoji: '🇻🇺' },
        WAVES: { symbol: '₿', emoji: '🪙' },
        WEMIX: { symbol: '₿', emoji: '🪙' },
        WOO: { symbol: '₿', emoji: '🪙' },
        WST: { symbol: 'T', emoji: '🇼🇸' },
        XAF: { symbol: 'Fr', emoji: '🇨🇫' },
        XAG: { symbol: 'XAG', emoji: '🪙' },
        XAU: { symbol: 'XAU', emoji: '🪙' },
        XAUT: { symbol: '₿', emoji: '🪙' },
        XBT: { symbol: '₿', emoji: '🪙' },
        XCD: { symbol: '$', emoji: '🇦🇬' },
        XCH: { symbol: '₿', emoji: '🪙' },
        XDC: { symbol: '₿', emoji: '🪙' },
        XDR: { symbol: 'XDR', emoji: '🌐' },
        XEC: { symbol: '₿', emoji: '🪙' },
        XEM: { symbol: '₿', emoji: '🪙' },
        XLM: { symbol: '₿', emoji: '🪙' },
        XMR: { symbol: '₿', emoji: '🪙' },
        XOF: { symbol: 'Fr', emoji: '🇧🇯' },
        XPD: { symbol: 'XPD', emoji: '🪙' },
        XPF: { symbol: '₣', emoji: '🇵🇫' },
        XPT: { symbol: 'XPT', emoji: '🪙' },
        XRP: { symbol: '₿', emoji: '🪙' },
        XTZ: { symbol: '₿', emoji: '🪙' },
        YER: { symbol: '﷼', emoji: '🇾🇪' },
        ZAR: { symbol: 'R', emoji: '🇿🇦' },
        ZEC: { symbol: '₿', emoji: '🪙' },
        ZIL: { symbol: '₿', emoji: '🪙' },
        ZMK: { symbol: 'ZK', emoji: '🇿🇲' },
        ZMW: { symbol: 'ZK', emoji: '🇿🇲' },
        ZWD: { symbol: 'Z$', emoji: '🇿🇼' },
        ZWG: { symbol: 'Z$', emoji: '🇿🇼' },
        ZWL: { symbol: 'Z$', emoji: '🇿🇼' }
    },

    formatNumber(number, maximumFractionDigits = 6) {
        return new Intl.NumberFormat('en-US', {
            minimumFractionDigits: 2,
            maximumFractionDigits: maximumFractionDigits
        }).format(number);
    },

    formatCurrency(amount, currencyCode) {
        const meta = this.currencyMeta[currencyCode.toUpperCase()] || { symbol: '', emoji: '' };
        return `${meta.symbol}${this.formatNumber(amount)} ${currencyCode.toUpperCase()}`;
    },

    formatDate(dateString) {
        return new Date(dateString).toLocaleDateString();
    },

    calculateChange(oldValue, newValue) {
        if (!oldValue || !newValue) return null;
        const change = ((newValue - oldValue) / oldValue) * 100;
        return change.toFixed(2);
    },

    parseAmount(expression) {
        try {
            const sanitizedExpression = expression.replace(/[^0-9+\-*/().]/g, '');
            return Function(`'use strict'; return (${sanitizedExpression})`)();
        } catch (e) {
            return parseFloat(expression) || 0;
        }
    },

    parseMultipleAmounts(input) {
        if (!input.trim()) return [0];
        return input
            .split(/[;；；؛；]/) 
            .map(amount => amount.trim())
            .filter(amount => amount)
            .map(amount => this.parseAmount(
                amount
                    .replace(/×/g, '*')
                    .replace(/÷/g, '/')
            ));
    }
};